/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.PharmacistTransaction;
import Model.CRUD;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author but-anonju_sd2022
 */
public class PharmacistEditMedicine extends javax.swing.JFrame {

//    public  JTable getEditMedicineTable() {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//    }

    CRUD crud = new CRUD();
    DefaultTableModel tm = new DefaultTableModel();
    PharmacistTransaction pharmacist = new PharmacistTransaction();

    static String medfor;
    static String genName;
    static String bName;
    static String price;
    static String qty;
    static String desc;

//        CREATE A NEW JTEXTFIELD
    JTextField medforForm = new JTextField(20);
    JTextField genNameForm = new JTextField(20);
    JTextField bNameForm = new JTextField(20);
    JTextField priceForm = new JTextField(20);
    JTextField qtyForm = new JTextField(20);
    JTextArea descForm = new JTextArea(10, 10);

    public static String getMedfor() {
        return medfor;
    }

    public String getGenName() {
        return genName;
    }

    public String getbName() {
        return bName;
    }

    public String getPrice() {
        return price;
    }

    public String getQty() {
        return qty;
    }

    public String getDesc() {
        return desc;
    }

    public JTextField getMedforForm() {
        return medforForm;
    }

    public JTextField getGenNameForm() {
        return genNameForm;
    }

    public JTextField getbNameForm() {
        return bNameForm;
    }

    public JTextField getPriceForm() {
        return priceForm;
    }

    public JTextField getQtyForm() {
        return qtyForm;
    }

    public JTextArea getDescForm() {
        return descForm;
    }

    public JTable getEditMedicineTable() {
        return editMedicineTable;
    }
    
    

    /**
     * Creates new form EditMedicine
     */
    public PharmacistEditMedicine() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        editMedicineTable = new javax.swing.JTable();
        backBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));

        editMedicineTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medicine For", "Generic Name", "Brand Name", "Price", "Quantity", "Description"
            }
        ));
        editMedicineTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMedicineTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(editMedicineTable);

        backBtn.setText("Back");
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(backBtn)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Edit Medicine");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void editMedicineTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMedicineTableMouseClicked
//        editMedicineTable.setModel(pharmacist.getAllData());
        int row = editMedicineTable.getSelectedRow();
// =================================================== WALA PA NI ============ DILI PA MA UPDATE ANG NAA SA DATABASE ======================================================
        medfor = editMedicineTable.getValueAt(row, 0).toString();
        genName = editMedicineTable.getValueAt(row, 1).toString();
        bName = editMedicineTable.getValueAt(row, 2).toString();
        price = editMedicineTable.getValueAt(row, 3).toString();
        qty = editMedicineTable.getValueAt(row, 4).toString();
        desc = editMedicineTable.getValueAt(row, 5).toString();
        edit();

    }//GEN-LAST:event_editMedicineTableMouseClicked

    private void backBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseClicked
        // TODO add your handling code here:
        PharmacistHomePage ph = new PharmacistHomePage();
        this.setVisible(false);
        ph.setVisible(true);
    }//GEN-LAST:event_backBtnMouseClicked

    public boolean edit() {
        boolean edited = false;
//        SET VALUE FOR EVERY JTEXTFIELD
        medforForm.setText(medfor);
        genNameForm.setText(genName);
        bNameForm.setText(bName);
        priceForm.setText(price);
        qtyForm.setText(qty);
        descForm.setText(desc);
//        INSTANCE OF THE POPUP TABLE TO EDIT
        Object[] obj = {
            "Medicine For : ", medforForm,
            "Generic name : ", genNameForm,
            "Brand name : ", bNameForm,
            "Price : ", priceForm,
            "Quantity : ", qtyForm,
            "Description : ", descForm
        };
        String update = "UPDATE medicine SET Med_For = ?, GenericName = ? , BrandName = ?, Price = , Quantity = ?, Description = ? WHERE BrandName =" + "\"" + bName + "\"" + ";";
//        POPUP TABLE TO EDIT
        int opt = JOptionPane.showConfirmDialog(rootPane, obj, "Edit datas", JOptionPane.OK_CANCEL_OPTION);
        Connection connection = new CRUD().connectToDB();
        if (opt == 0) {
            try {
                System.out.println(bName);
                PreparedStatement psmt = connection.prepareStatement(update);
                psmt.setString(1, medforForm.getText());
                psmt.setString(2, genNameForm.getText());
                psmt.setString(3, bNameForm.getText());
                psmt.setDouble(4, Double.parseDouble(priceForm.getText()));
                psmt.setInt(5, Integer.parseInt(qtyForm.getText()));
                psmt.setString(6, descForm.getText());
                psmt.executeUpdate();
//                psmt.executeUpdate(update);

                tm.setRowCount(0);
                connection.close();

                edited = true;

            } catch (SQLException ex) {
                edited = false;
            }
        }
        return edited;
    }

    public void getAllData() {
        try {
            tm = (DefaultTableModel) editMedicineTable.getModel();
            // TODO add your handling code here:
            String query = "SELECT * FROM medicine";
            Connection connection = crud.connectToDB();
            ResultSet rs = crud.getData(query);
            while (rs.next()) {
                tm.addRow(new Object[]{rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7)});
            }
            connection.close();
        } catch (Exception ex) {
            Logger.getLogger(PharmacistEditMedicine.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PharmacistEditMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PharmacistEditMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PharmacistEditMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PharmacistEditMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PharmacistEditMedicine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTable editMedicineTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
