/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.CRUD;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
//import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author but-anonju_sd2022
 */
public class UserLogin extends javax.swing.JFrame {

    CRUD crud = new CRUD();
    String generatedPass;
    List users = new ArrayList();
    String account_saved_Db = null;
    String passWord_saved_Db = null;
    String role_saved_db = null;
    static String user;
    static String pass;
    CustomerHomePage tp = new CustomerHomePage();

    /**
     * Creates new form Login
     */
    public UserLogin() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        loginL = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        loginbtn = new javax.swing.JButton();
        signInBtn = new javax.swing.JButton();
<<<<<<< HEAD
        input_login_password = new javax.swing.JPasswordField();
        input_login_uname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
=======
        inputPass = new javax.swing.JPasswordField();
        inputUname = new javax.swing.JTextField();
        passL = new javax.swing.JLabel();
        unameL = new javax.swing.JLabel();
        askAccL = new javax.swing.JLabel();
>>>>>>> 6844e25c058211af9288e0820bfdd8c7e55c196d

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

<<<<<<< HEAD
        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Login");
=======
        loginL.setFont(new java.awt.Font("Monotype Corsiva", 1, 48)); // NOI18N
        loginL.setForeground(new java.awt.Color(255, 153, 153));
        loginL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginL.setText("Login");
>>>>>>> 6844e25c058211af9288e0820bfdd8c7e55c196d

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));

        loginbtn.setText("Login");
        loginbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginbtnMouseClicked(evt);
            }
        });

        signInBtn.setText("Sign in");
        signInBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signInBtnMouseClicked(evt);
            }
        });

        inputPass.setText("password");

        inputUname.setText("username");

        passL.setText("Password : ");

        unameL.setText("Username : ");

        askAccL.setText("Don't have an account yet ?");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(loginbtn))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(signInBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passL)
                            .addComponent(unameL))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputPass, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputUname, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(askAccL)))
                .addGap(0, 99, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputUname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unameL))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passL))
                .addGap(37, 37, 37)
                .addComponent(loginbtn)
                .addGap(37, 37, 37)
                .addComponent(askAccL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(signInBtn)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 153, 153));
        jLabel5.setText("Kind's Pharmacy");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
<<<<<<< HEAD
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
=======
                    .addComponent(loginL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
>>>>>>> 6844e25c058211af9288e0820bfdd8c7e55c196d
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
<<<<<<< HEAD
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
=======
                .addComponent(loginL, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
>>>>>>> 6844e25c058211af9288e0820bfdd8c7e55c196d
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginbtnMouseClicked
        // TODO add your handling code here:
        user = inputUname.getText(); // This will get the user input in the username text field
        pass = inputPass.getText(); // This will get the user input in the password text field
//        encryptPassword(pass); // This will encrypt the password that was entered by the user but not used for now :)

        try {

            String accountQuery = "SELECT Username, Password, Role FROM users WHERE Username=" + "\"" + user + "\"" + ";"; // This will get the Username and password from the table users that is equal to the user input
            Connection connection = crud.connectToDB(); // Connect to the database
            ResultSet rsAcc = crud.getData(accountQuery); // Get the the result accountQuery from the database

            while (rsAcc.next()) {
                account_saved_Db = rsAcc.getString("Username");
                passWord_saved_Db = rsAcc.getString("Password");
                role_saved_db = rsAcc.getString("Role");
            }
            connection.close(); // Close the connection to the database
        } catch (SQLException ex) {
            // This means that 
            System.out.println(ex.getMessage());
        }
// CHECK IF THE VALUE OF THE Username, Password INPUT AND THE IS EQUAL TO THE Username, Password TAKEN FROM THE DATA BASE AND THE ROLE IS Customer
        if (user.equals(account_saved_Db) && pass.equals(passWord_saved_Db) && role_saved_db.equals("Customer")) {
            JOptionPane.showMessageDialog(rootPane, "Customer");
            tp.setUsername(user);
            this.setVisible(false);
            tp.setVisible(true);
        } // CHECK IF THE VALUE OF THE Username, Password INPUT AND THE IS EQUAL TO THE Username, Password TAKEN FROM THE DATA BASE AND THE ROLE IS Pharmacist 
        else if (user.equals(account_saved_Db) && pass.equals(passWord_saved_Db) && role_saved_db.equals("Pharmacist")) {
            JOptionPane.showMessageDialog(rootPane, "Pharmacist");
            this.setVisible(false);
            PharmacistHomePage ph = new PharmacistHomePage();
            ph.setVisible(true);
        } else { // ELSE IT WILL DISPLAY ERROR
            JOptionPane.showMessageDialog(rootPane, "Di Lagi Ka Sud?\n" + "username : " + account_saved_Db + " = " + user + "\npassword : " + passWord_saved_Db + " = " + pass, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_loginbtnMouseClicked

    private void signInBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signInBtnMouseClicked
        // TODO add your handling code here:ou
        UserRegister reg = new UserRegister();
        reg.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_signInBtnMouseClicked

    // This is the method in encrypting the user input password
//    private String encryptPassword(String passw) {
//        try {
//            MessageDigest md = MessageDigest.getInstance("MD5");
//
//            md.update(passw.getBytes());
//
//            byte[] bytes = md.digest();
//
//            StringBuilder sb = new StringBuilder();
//
//            for (int i = 0; i < bytes.length; i++) {
//                sb.append(Integer.toString((bytes[i] & 0xff) + 0x100, 16).substring(1));
//            }
//            generatedPass = sb.toString();
//        } catch (NoSuchAlgorithmException ex) {
//            ex.printStackTrace();
//        }
//        return generatedPass;
//    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
<<<<<<< HEAD
    private javax.swing.JPasswordField input_login_password;
    private javax.swing.JTextField input_login_uname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
=======
    private javax.swing.JLabel askAccL;
    private javax.swing.JPasswordField inputPass;
    private javax.swing.JTextField inputUname;
>>>>>>> 6844e25c058211af9288e0820bfdd8c7e55c196d
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel loginL;
    private javax.swing.JButton loginbtn;
    private javax.swing.JLabel passL;
    private javax.swing.JButton signInBtn;
    private javax.swing.JLabel unameL;
    // End of variables declaration//GEN-END:variables
}
